### PR TITLE
fix: fix infinite loop+add empty search action+add focus search

### PR DESCRIPTION
**Pull request by JuliaNsk**
fix: fix infinite loop+add empty search action+add focus search field

### CODE REVIEW

**Comment by JuliaNsk** [comment]
How can I make empty search field while toggle dropdown? without changes?

**Comment by pkempenaers** [comment]
There is an onClose event and there is a searchFilter attribute that can be set

**Comment by JuliaNsk** [comment]
Okey, I ll try it, and another question: I have long lists, more than 100 items and it's hard to find items that are ckicked and I want to have this items at the top of the list, maybe you code already have this feature, but I can't find it?

**Comment by pkempenaers** [comment]
You can sort the list externally and that should be reflected in the component

**Comment by JuliaNsk** [comment]
I have done it, but I have a lot of pages with this feature and It's hard to add a big part of code to each controller, It would be greate to have one way to resolve it

**Comment by pkempenaers** [comment]
There currently is nothing implemented that allows to do that easily

**Comment by JuliaNsk** [comment]
Do you think it will be a good feature? Then I ll try to implement it to your library.

**Comment by pkempenaers** [comment]
As long as it is configurable I don't see a reason why not to add it.

**Comment by JuliaNsk** [comment]
Okey, than I ll try to do this. Thank you

**Pull request merged**
