### PR TITLE
Allow custom trigger element using transclusion

### PR DESCRIPTION
**Pull request by dscerri**
Support custom elements as the dropdown toggle, rather than being locked in to using a button with specific text.

See Plunkr for demo - https://plnkr.co/edit/B1zK6Wo4cXeDtxxQJwSr?p=preview

### CODE REVIEW

**Comment by pkempenaers** [comment]
Am I missing something in your plnkr? I can't see the custom trigger, both dropdowns seem to use a button.

**Comment by dscerri** [comment]
Oops, yes sorry that was pointing at the wrong branch.

See https://plnkr.co/edit/wcoZl2CWcYFtTwtPF1mQ?p=preview

**Comment by pkempenaers** [comment]
Should work in beta.5. Next time try to create a clean PR (I had to revert some commits and that resulted in this PR not being marked as merged, You'll see however that your commit has been included)

**Comment by pkempenaers** [comment]
I've noticed that in the current implementation you can't have whitespace between opening and closing tags of the component. I've changed the transclusion to a named transclusion.
I've modified your plnkr [here](https://plnkr.co/edit/g3EuDPdw47rnS1fm1lzX?p=preview)

**Pull request closed without merging**
