### PR TITLE
Added type check on className to make sure it's a string before splitting

### PR DESCRIPTION
**Pull request by samny**
Fixes issue #49

### CODE REVIEW

**Comment by joehany** [comment]
@danpaulsmith Thank you for the great component, we appreciate if you can merge this fix.

**Comment by lingareddy18** [comment]
I can still reproduce this issue. The error says "Uncaught TypeError: target.className.split is not a function". i had tried with the committed code, i.e above linked code. Please let me know on this.

**Comment by danpaulsmith** [comment]
@saadshahd it's in Sammy's fork

https://raw.githubusercontent.com/samny/angularjs-dropdown-multiselect/master/dist/angularjs-dropdown-multiselect.min.js

**Comment by danpaulsmith** [comment]
Feel free to nudge this PR on the main repo - https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/204/commits

**Pull request closed without merging**
