### PR TITLE
fix: add feature "selectedToTop"

### PR DESCRIPTION
**Pull request by JuliaNsk**

### CODE REVIEW

**Comment by JuliaNsk** [comment]
Looking forward for your answer :)

**Comment by pkempenaers** [comment]
Still seems like you use lodash. I'll try to implement the pluck method myself

**Comment by JuliaNsk** [comment]
I have already done it,  var selected contains all ids, I just forgot to replace it

**Comment by pkempenaers** [comment]
Can you commit that? then I can merge this PR

**Comment by JuliaNsk** [comment]
Done

**Comment by pkempenaers** [comment]
I'm going to add documentation and then release it

**Comment by JuliaNsk** [comment]
Okey. Thank you, waitinf for release:)

**Pull request merged**
