### PR TITLE
Cleaned up bower.json

### LINKED ISSUE #212: angularjs-dropdown-multiselect#1.5.2 is not compatible with Angular 1.5
My Current Angular version is 1.5.

$ bower install angularjs-dropdown-multiselect --save
bower angularjs-dropdown-multiselect#\*           cached https://github.com/dotansimha/angularjs-dropdown-multiselect.git#1.5.2
bower angularjs-dropdown-multiselect#\*         validate 1.5.2 against https://github.com/dotansimha/angularjs-dropdown-multiselect.git#*
bower angular#~1.2.0                             cached https://github.com/angular/bower-angular.git#1.2.29
bower angular#~1.2.0                           validate 1.2.29 against https://github.com/angular/bower-angular.git#~1.2.0
bower lodash#~2.4.1                              cached https://github.com/lodash/lodash.git#2.4.2
bower lodash#~2.4.1                            validate 2.4.2 against https://github.com/lodash/lodash.git#~2.4.1
bower angular#~1.x                               cached https://github.com/angular/bower-angular.git#1.5.0
bower angular#~1.x                             validate 1.5.0 against https://github.com/angular/bower-angular.git#~1.x
**bower                                         ECONFLICT Unable to find suitable version for angular**

### PR DESCRIPTION
**Pull request by pkempenaers**
Cleaned up angular dependency

Fixes #212

You can install this specific fork with
`bower install myforce-angularjs-dropdown-multiselect`

### CODE REVIEW

**Comment by Taranys** [comment]
:+1:

**Comment by Machadalo** [comment]
Still unable to install by using
bower install myforce-angular-dropdown-multiselect

Getting error  "ENOTFOUND Package myforce-angular-dropdown-multiselect not found"

**Comment by pkempenaers** [comment]
Sorry it's bower install myforce-angularjs-dropdown-multiselect

**Comment by Machadalo** [comment]
@Pieter Hey thanks a lot for the quick response, it is working.

On Fri, Mar 11, 2016 at 1:58 PM, Pieter Kempenaers <notifications@github.com

**Comment by Machadalo** [comment]
What is the name of the module and dependency to be injected in angular and
bower.json respectively?

**Comment by pkempenaers** [comment]
bower package name is 'myforce-angularjs-dropdown-multiselect'
module name 'angularjs-dropdown-multiselect'
directive name 'ng-dropdown-multiselect'

documentation can be found at http://myforce.github.io/angularjs-dropdown-multiselect/#/

**Comment by Machadalo** [comment]
Hi Pieter,

I'm trying to change the default value of displayProp from label to
student_name (as this variable contains the data which I want to show on
screen), after doing this also data is not getting displayed in drop down.

Below is the code:
var student_name = '';

$scope.example14settings = {
scrollableHeight: '100px',
 scrollable: true,
 dynamicTitle: false,
displayProp: student_name
};


On Fri, Mar 11, 2016 at 4:04 PM, Pieter Kempenaers <notifications@github.com

**Comment by pkempenaers** [comment]
Could you please make an issue at [my forked repo](https://github.com/myforce/angularjs-dropdown-multiselect)? This will make it easier for me to track this. I'll take a look at it once you've done that

**Pull request merged**
