### PR TITLE
fix: focus searchfield first when search is enabled

### PR DESCRIPTION
**Pull request by JuliaNsk**
fix: focus searchfield first when search is enabled

### CODE REVIEW

**Comment by pkempenaers** [comment]
Could you please rewrite this as a fix (so not as a setting but simply focus searchfield first when search is enabled) and could you make your PR to dotansimha:fix instead of master?

Thanks

**Comment by JuliaNsk** [comment]
Okey

**Comment by pkempenaers** [comment]
I can't really merge this as you have too many changes, could you please make it so that only necessary changes are checked in? (so no white space changes, no package.json and no bower.json changes?)

**Comment by JuliaNsk** [comment]
Okey, I ll go through my changes and refactor it, now we use my branch with changes in our project, but we really want to use your library directly --Best wishes,Julia NoskoDeveloperSkype: little_angel2912E-mail: julia.nosko@onix-systems.com Onix-Systems, LLCUltimate IT Consultinghttp://onix-systems.com08.03.2017, 11:07, "Pieter Kempenaers" <notifications@github.com>:I can't really merge this as you have too many changes, could you please make it so that only necessary changes are checked in? (so no white space changes, no package.json and no bower.json changes?)

**Comment by JuliaNsk** [comment]
I have make new request with all necessary changes

**Pull request closed without merging**
