### PR TITLE
fix: problem with map "selectedtotop"

### PR DESCRIPTION
**Pull request by JuliaNsk**

### CODE REVIEW

**Comment by pkempenaers** [comment]
I 've already noticed this, I'm making a 2.0.0-beta where for single selection the selectedmodel is still an array so this PR won't be needed. Planning on releasing beta.1 in the next few hours

**Comment by JuliaNsk** [comment]
Okey, thank you. waiting for releas

**Comment by pkempenaers** [comment]
2.0.0-beta.1 has been released

**Comment by JuliaNsk** [comment]
I have already try it, but selectedtotop doesn't work for me:(

**Comment by pkempenaers** [comment]
The example at the [documentation](http://dotansimha.github.io/angularjs-dropdown-multiselect/docs/#/main) is working. (it's the last example). Can you replicate what you want to do in plnkr? Then I can have a closer look.

**Comment by JuliaNsk** [comment]
I can't add your library in plnkr

**Comment by pkempenaers** [comment]
You can use https://rawgit.com/dotansimha/angularjs-dropdown-multiselect/master/component/component.js

**Comment by JuliaNsk** [comment]
I have add your example from documentation to my page and it doesn't work. I can't imagine what the problem is. Another options works but this doesn't

**Comment by pkempenaers** [comment]
Do you want me to create a working plnkr? You can then fork and "break" that plnkr, then I can see what is going wrong.

**Comment by JuliaNsk** [comment]
https://plnkr.co/edit/m8Q9FmQ3sMGzV7ORdiP5?p=preview
Could you look throught it? What's wrong with plunker?

**Comment by pkempenaers** [comment]
I've changed some things:
 - order of loading of scripts
 - added dependency in initiating of plunker module
 - updated angular 1.4 to 1.5

https://plnkr.co/edit/ztsUl3Y5Gs2te6aSsB2U?p=preview

**Comment by JuliaNsk** [comment]
I see. It doesnt work with angular 1.4

**Comment by pkempenaers** [comment]
Angular 1.4 is not officialy supported by the angular team anymore (only 1.2, 1.5 and 1.6beta) are. Migrating to 1.5 from 1.4 also isn't that much work (if any)

**Comment by Knguyen21** [comment]
I have Angular 1.6 and it doesn't work for me.

**Pull request closed without merging**
