### PR TITLE
Add support for Lodash 4.0

### PR DESCRIPTION
**Pull request by victorjacobs**
The library broke when using Lodash 4.0 (_.contains no longer exists).

### CODE REVIEW

**Comment by YannBertrand** [comment]
+1

**Comment by calamarico** [comment]
LGTM, merge!

**Comment by Masadow** [comment]
:+1:

**Comment by iamkoby** [comment]
+1

**Comment by pkempenaers** [comment]
Hi guys I've fixed this (by fully removing the lodash dependency) and some other things (even some extra features) on a fork and i'm actively maintaining it.
You can install that fork using
`bower install myforce-angularjs-dropdown-multiselect`

The documentation for that specific fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/). and the fork itself [here](https://github.com/myforce/angularjs-dropdown-multiselect)

**Comment by pkempenaers** [comment]
Now also in this version

**Pull request closed without merging**
